eureka:
  client:
    service-url:
      defaultZone: http://localhost:9317/eureka
spring:
  application:
    name: admin-server
  boot:
    admin:
      routes:
        endpoints: env,metrics,dump,jolokia,info,configprops,trace,logfile,refresh,flyway,liquibase,heapdump,loggers,auditevents,hystrix.stream,activiti
      turbine:
        clusters: default
        location: turbine-service
server:
  port: 5000
management:
  security:
    enabled: false
logging:
  file: "logs/boot-admin.log"

