eureka:
  client:
    service-url:
      defaultZone: http://localhost:9317/eureka
server:
  port: 8765
spring:
  application:
    name: feign-hi-client
  zipkin:
    base-url: http://localhost:9411
  sleuth:
    sampler:
      percentage: 1.0
feign:
  hystrix:
    enabled: true