eureka:
  client:
    service-url:
      defaultZone: http://localhost:9317/eureka
server:
  port: 8762
spring:
  application:
    name: hi-client
  zipkin:
    base-url: http://localhost:9411
  sleuth:
    sampler:
      percentage: 1.0
logging:
  file: "logs/hi-client.log"
management:
  security:
    enabled: false