eureka:
  client:
    service-url:
      defaultZone: http://localhost:9317/eureka
spring:
  application:
    name: turbine-service
server:
  port: 8769
turbine:
  app-config: hi-client,hello-client
  cluster-name-expression: new Sring("default")
  aggregator:
    clusterConfig: default
management:
  security:
    enabled: false