eureka:
  client:
    service-url:
      defaultZone: http://localhost:9317/eureka
server:
  port: 3159
spring:
  application:
    name: zuul-service
  zipkin:
    base-url: http://localhost:9411
  sleuth:
    sampler:
      percentage: 1.0
zuul:
  routes:
    hiapi:
      path: /hiapi/**
      serviceId: feign-hi-client
    helloapi:
      path: /helloapi/**
      serviceId: hello-client
  prefix: /v1