eureka:
  client:
    service-url:
      defaultZone: http://localhost:9317/eureka
server:
  port: 9411
spring:
  application:
    name: zipkin-server
zipkin:
  storage:
    type: elasticsearch
    StorageComponent: elasticsearch
    elasticsearch:
      cluster: elasticsearch
      max-request: 30
      index: zipkin
      index-shards: 3
      index-replicas: 1
      host: localhost:9200