spring:
  application:
    name: eureka-server
server:
  port: 9317
eureka:
  instance:
    hostname: server.eureka
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://server.eureka:${server.port}/eureka