spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/yfzm/SpringcloudConfig
          search-paths: kiwi
      label: master
  application:
    name: config-server
server:
  port: 8792
eureka:
  client:
    service-url:
      defaultZone: http://localhost:9317/eureka/